# Rhode Island Counties (Zipped with Municipalities - DO NOT CHANGE ORDER)
rhode_island_counties = ['Bristol County',
                        'Bristol County',
                        'Bristol County',
                        'Kent County',
                        'Kent County',
                        'Kent County',
                        'Kent County',
                        'Kent County',
                        'Newport County',
                        'Newport County',
                        'Newport County',
                        'Newport County',
                        'Newport County',
                        'Newport County',
                        'Providence County',
                        'Providence County',
                        'Providence County',
                        'Providence County',
                        'Providence County',
                        'Providence County',
                        'Providence County',
                        'Providence County',
                        'Providence County',
                        'Providence County',
                        'Providence County',
                        'Providence County',
                        'Providence County',
                        'Providence County',
                        'Providence County',
                        'Providence County',
                        'Washington County',
                        'Washington County',
                        'Washington County',
                        'Washington County',
                        'Washington County',
                        'Washington County',
                        'Washington County',
                        'Washington County']
                        
# Rhode Island Minicipalities (Zipped with Counties - DO NOT CHANGE ORDER)
rhode_island_municipalities = ['Barrington',
                              'Warren',
                              'Bristol',
                              'Coventry',
                              'West Greenwich',
                              'East Greenwich',
                              'West Warwick',
                              'Warwick',
                              'Portsmouth',
                              'Tiverton',
                              'Jamestown',
                              'Newport',
                              'Middletown',
                              'Little Compton',
                              'Foster',
                              'Scituate',
                              'Glocester',
                              'Burrillville',
                              'North Smithfield',
                              'Smithfield',
                              'Johnston',
                              'Cranston',
                              'Woonsocket',
                              'Cumberland',
                              'Lincoln',
                              'Central Falls',
                              'Pawtucket',
                              'North Providence',
                              'Providence',
                              'East Providence',
                              'Westerly',
                              'Charlestown',
                              'South Kingstown',
                              'Narragansett',
                              'Hopkinton',
                              'Richmond',
                              'Exeter',
                              'North Kingstown']
